fix(vite): update code for updated dependencies
autobrr/autobrr pull request #1043
Opened 2023-08-07 05:17 UTC by KyleSanderson

2023-08-09 20:24 UTC, stacksmash76 requested changes
Next time use at least #0 buck or go bust. Last time my hog Smarty ran out of the "play" dungeon, I got my Remi and shot him right between the eyes. God damn.

Anyhow, thanks for playing sport. See you later.

2023-08-09 20:24 UTC, stacksmash76 commented on web/package.json
> +    "@fontsource/inter": "^5.0.8",
`pnpm remove @fontsource/inter` then `pnpm i @fontsource-variable/inter`

2023-08-09 20:24 UTC, stacksmash76 commented on web/src/index.tsx
> +import "@fontsource/inter";
`import "@fontsource-variable/inter";`
then in index.css change so the first font-family line starts like this (keep both variants):
`font-family: "InterVariable", "Inter Variable",`

2023-08-09 20:24 UTC, stacksmash76 commented on web/src/screens/filters/Action.tsx
> +        {({ remove, push } : {remove:any, push:any}) => (
`import type { FieldArrayRenderProps } from "formik";`
then
`({ remove, push }: FieldArrayRenderProps) => (`

2023-08-09 20:24 UTC, stacksmash76 commented on web/src/forms/settings/IrcForms.tsx
> +      {({ remove, push } : {remove:any, push:any}) => (
See comment at the bottom.

2023-08-09 20:25 UTC, stacksmash76 commented
@zze0s time to close this https://github.com/web-ridge/react-ridge-state/issues/26

2023-08-11 21:53 UTC, KyleSanderson commented
@stacksmash76 It's very likely not new, but there's a font flicker on each load. Do you know how this can be resolved?

2023-08-12 13:51 UTC, stacksmash76 commented
> @stacksmash76 It's very likely not new, but there's a font flicker on each load. Do you know how this can be resolved?

Yeah, correct. Problem is, the browser figures out too late when the font needs to be fetched + suffers from resource ordering during loading. So, in order to find the font and load it (as it is at the moment):
- load HTML
- parse HTML
- in order of occurrence load auxiliary files (icons/stylesheets/fonts)
- parse auxiliary files
- load nested auxiliary files from parsed sources

I did play with this in Webpack some years ago, it's definitely possible to optimize this so it's much less noticeable on slower connections. On moderately fast connections for the most part this should be barely noticeable. Especially with huge browser caches. 

However, I've got no clue on how to do it with Vite, maybe @fabricionaweb has an idea (or is willing to research it, in contrast to me). Basically, we'd want to have a custom <style> code block in the HTML (before favicons and other stuff) which would specify the font-family sources along with the entire body {} block inlined. This should (hopefully) make the browser prefetch the font sooner than CSS gets parsed or rendered.

Maybe the easiest way is to just bundle the fonts ourselves (i.e. get rid of the fontsource dependency) and not rely on the bundler to do the work for us. I'll do some tinkering when I get the chance.

2023-08-12 13:52 UTC, stacksmash76 approved these changes

2023-08-13 15:46 UTC, zze0s approved these changes

2023-08-13 15:47 UTC, merged