feat(tests): Verify autobrr.com URLs
autobrr/autobrr pull request #1253
Opened 2023-11-09 06:49 UTC by s0up4200

A test aimed at verifying that all references to autobrr.com are resolving as expected. The test makes HTTP GET requests, checking for any that return a 404 status. This should help maintain the integrity of our documentation links.

2023-11-09 07:17 UTC, KyleSanderson commented
Excellent start! What you likely want to do is to scan through the .go files and pull links from there. Maybe there's a grep library to help facilitate this?

2023-11-13 21:55 UTC, KyleSanderson approved these changes

2023-11-14 20:01 UTC, zze0s requested changes
Cool and useful idea!

Minor thing but it does not really belong in the `http` package since it checks external links.

Could you move it into  a new dir called `docs` in the test dir? 😄

2023-11-14 20:11 UTC, s0up4200 commented
> Cool and useful idea!
> 
> Minor thing but it does not really belong in the `http` package since it checks external links.
> 
> Could you move it into a new dir called `docs` in the test dir? 😄

Done 👍

2023-11-14 20:41 UTC, zze0s approved these changes

2023-11-14 20:41 UTC, merged