feat(filter):implement min and max uploader count filtering
autobrr/autobrr pull request #1339
Opened 2024-01-02 08:38 UTC by luckyboy

2024-01-02 08:46 UTC, KyleSanderson reviewed
Neat! Doesn't look like freeleech time is wired up yet, but off to a very solid start.

2024-01-02 08:46 UTC, KyleSanderson commented on internal/database/sqlite.go
> +	db.log.Info().Msgf("PRAGMA user_version %d", version)
snuck-in perhaps?

2024-01-02 09:03 UTC, luckyboy commented on internal/database/sqlite.go
> +	db.log.Info().Msgf("PRAGMA user_version %d", version)
Ha, it's indeed snuck-in.

2024-01-02 09:10 UTC, luckyboy commented
> Neat! Doesn't look like freeleech time is wired up yet, but off to a very solid start.

Freeleech time is defined by some site, i can't find a way to extract those information from current torznab implement. Maybe i should remove this part from this PR.

2024-01-02 14:35 UTC, s0up4200 requested changes

2024-01-02 14:35 UTC, s0up4200 commented on web/src/screens/filters/sections/Advanced.tsx
> +          <p>Number of max seeders as specified by the respective unit.</p>
```suggestion
          <p>Number of min seeders as specified by the respective unit.</p>
```

2024-01-02 16:21 UTC, zze0s reviewed
Good stuff!!

Some suggestions:

* I suggest changing `uploader` to `seeder` for db and structs
* Add min/max leecher filters like seeder already have
* Add a new filter tab/page called Feeds where these Feeds specific settings are grouped

We have recently discussed about moving the Feed Max Age setting from Feed settings to the filter. It probably makes more sense in the filter. I can take care of that in this or a new PR.

2024-01-03 01:20 UTC, zze0s commented
No need to close the PR. If you push to the same branch they will show up here.

2024-01-03 02:00 UTC, luckyboy commented
> No need to close the PR. If you push to the same branch they will show up here.

Thank you, i'm still adapting to github. i will try to improve this PR anyway.

2024-01-03 04:42 UTC, closed without merging

2024-01-03 04:46 UTC, luckyboy commented
Created a new PR #1342, leechers filtering is included. And the filter settings for seeders and leechers ware arranged to RSS/Torznab/Newznab-specific(FeedSpecific).