feat(web): redirect to login on expired cookie
autobrr/autobrr pull request #201
Opened 2022-03-23 18:44 UTC by ludviglundgren

Redirect to `login` on expired cookie session.

2022-03-23 19:22 UTC, stacksmash76 commented on web/src/api/APIClient.ts
> +                AuthContext.set([{ username: "", isLoggedIn: false }] as any)
I'd also clear the cookies first by doing:
```
cookies = new Cookies();
cookies.remove("user_session");
```
and afterwards resetting the AuthContext object.

Cookies can be imported from react-cookies: ```import { Cookies } from "react-cookie";```

2022-03-23 19:46 UTC, stacksmash76 requested changes
Needs a few adjustments. Changes made to App.tsx seem not to be needed.

There's a rather small problem with our solution: the promise returned by HttpClient needs to be cancelled when it returns the control flow to react-query. When the promise gets returned, react-query will try to refresh the component which made this request, but it will be unable to since firstly the parent (i.e. App) component will get refreshed, which will unload the child HttpClient-caller component before react-query gets to return data to it, at which point -- kaboom:
```
Error: Unauthorized
    at APIClient.ts:32:1
react_devtools_backend.js:3973 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Base (http://localhost:3000/static/js/bundle.js:7844:79)
    at Protected
```
   
See https://juliangaramendy.dev/blog/use-promise-subscription and https://gist.github.com/pygy/6290f78b078e22418821b07d8d63f111. IIRC, I think react-error-boundary handles this without leakage, but not sure. Might be a bandaid fix to a bullet wound.

2022-03-23 19:46 UTC, stacksmash76 commented on web/src/App.tsx
> +    const [authContext, setAuthContext] = AuthContext.use();
I'd say that all the changes made in this file are unneeded. I've tested the solution proposed in my two comments from below and it works as expected -- on an invalid cookie, upon the first next network activity, the user gets logged out and the cookie gets cleared.

2022-03-26 13:31 UTC, ludviglundgren commented
Made the suggested changes and that simplifies it. It still gives warning about `update in unmounted component`, but thats fine.

My first solution with the check to validate might have been a bit over-engineered for this case but the overall pattern of that isn't bad.

2022-03-26 17:51 UTC, stacksmash76 approved these changes
Looks good to me!

2022-03-26 18:46 UTC, merged