Fix Issue 636 - fail to parse torrent size on some RSS feeds
autobrr/autobrr pull request #667
Opened 2023-01-22 06:57 UTC by ghoto

When some RSS feeds have `Enclosure->Length` fixed size, autobrr fails to retrieve the size that's included in `Custom->Size`.

The previous logic used `custom->size` when `enclosure->length` was 0. But as stated in a previous issue, this `enclosure->length` can be a fixed length unrelated to the torrent. Therefore this value can be 0, fixed length, or the real one.

This modification will pick `custom->size` whenever is defined. When it's not it will use the former.

2023-01-22 18:20 UTC, KyleSanderson requested changes
Thank you very much for the contribution. Can you please revert the module changes (if there's a problem with the existing function, that should be fixed instead).

2023-01-22 18:20 UTC, KyleSanderson commented on internal/feed/rss.go
> +	"github.com/dustin/go-humanize"
Can you revert this?

2023-01-22 18:20 UTC, KyleSanderson commented on internal/feed/rss.go
> +		s, err := humanize.ParseBytes(size)
Ditto.

2023-01-22 18:23 UTC, ghoto commented
What do you mean with the existing function?

2023-01-22 21:30 UTC, ghoto commented
@KyleSanderson I moved the logic to `ParseSizeBytesString`. I fixed another potential bug on the function that would reset the size of the Release to 0 if the string passed to the function was malformed.

2023-01-22 21:40 UTC, KyleSanderson approved these changes

2023-01-29 15:17 UTC, zze0s reviewed
If we are making changes then might be good to check for not only enclosure size difference but quite a bit of feeds set the enclosure size to a static `39399` on all items.

While it could happen that something actually have that exact size, it's imo unlikely.

2023-02-05 18:11 UTC, zze0s approved these changes

2023-02-05 18:18 UTC, merged